server:
  port: 8002
# 确保 Spring Boot 提供静态资源
spring:
  resources:
   static-locations: classpath:/static/
  application:
    name: web

github:
  client-id: Ov23lieVPextjk6cLzm6
  client-secret: a7ab7a4bd4ab02b029a4ad370b671be5e1272aba
  redirect-uri: http://localhost:8002/github/callback